name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  check-format:
    name: Check Format
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install SwiftFormat
      run: brew install swiftformat

    - name: Check Format
      run: swiftformat . --lint

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13, macos-14]
        swift-version: ['5.9', '5.10']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: ${{ matrix.swift-version }}
    
    - name: Cache Swift packages
      uses: actions/cache@v4
      with:
        path: .build
        key: ${{ runner.os }}-swift-${{ matrix.swift-version }}-${{ hashFiles('Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-swift-${{ matrix.swift-version }}-
          ${{ runner.os }}-swift-
    
    - name: Build
      run: swift build -v
    
    - name: Run tests
      run: swift test -v
    
    - name: Build CLI tool
      run: swift build -c release --product HeifThumbnailerCLI

  build-release:
    name: Build Release
    runs-on: macos-latest
    needs: [test, lint]
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: '5.10'
    
    - name: Build release binary
      run: |
        swift build -c release --product HeifThumbnailerCLI
        cp .build/release/HeifThumbnailerCLI ./heif-thumbnailer
    
    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: heif-thumbnailer-macos
        path: heif-thumbnailer
        retention-days: 30 