name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13, macos-14]
        swift-version: ['5.9', '5.10']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: ${{ matrix.swift-version }}
    
    - name: Cache Swift packages
      uses: actions/cache@v4
      with:
        path: .build
        key: ${{ runner.os }}-swift-${{ matrix.swift-version }}-${{ hashFiles('Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-swift-${{ matrix.swift-version }}-
          ${{ runner.os }}-swift-
    
    - name: Build
      run: swift build -v
    
    - name: Run tests
      run: swift test -v
    
    - name: Build CLI tool
      run: swift build -c release --product HEICThumbnailerCLI

  lint:
    name: SwiftLint
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: SwiftLint
      uses: norio-nomura/action-swiftlint@3.2.1
      with:
        args: --strict

  build-release:
    name: Build Release
    runs-on: macos-latest
    needs: [test, lint]
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: '5.10'
    
    - name: Build release binary
      run: |
        swift build -c release --product HEICThumbnailerCLI
        cp .build/release/HEICThumbnailerCLI ./heic-thumbnailer
    
    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: heic-thumbnailer-macos
        path: heic-thumbnailer
        retention-days: 30 